import { BellDot, Clock3, RadioTower, Siren, Sparkles } from "lucide-react";
import { riskClass, riskGlow } from "@/lib/risk";

export function AlertsPanel({ alerts = [] }) {
  const latestAlert = alerts[0];

  return (
    <section className="panel overflow-hidden p-0">
      <div className="border-b border-slate-200/80 px-5 py-5">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-red-50 p-3 text-red-600">
              <BellDot className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-slate-950">Alerts Panel</h2>
              <p className="text-sm text-slate-500">Rolling incident feed generated by live camera workers.</p>
            </div>
          </div>
          <div className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
            {alerts.length} Active Log
          </div>
        </div>

        {latestAlert ? (
          <div className={`mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-gradient-to-r ${riskGlow[latestAlert.risk] || riskGlow.Low}`}>
            <div className="flex items-start justify-between gap-4 px-4 py-4">
              <div className="flex items-start gap-3">
                <div className="rounded-2xl bg-white/85 p-2.5 text-slate-900">
                  <Siren className="h-4 w-4" />
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Latest Incident</p>
                  <p className="mt-1 text-sm font-semibold text-slate-950">{latestAlert.zoneName}</p>
                  <p className="mt-1 text-sm text-slate-700">{latestAlert.message}</p>
                </div>
              </div>
              <span className={`${riskClass(latestAlert.risk)} rounded-full bg-white/75`}>
                {latestAlert.risk}
              </span>
            </div>
          </div>
        ) : null}
      </div>

      <div className="max-h-[34rem] overflow-y-auto px-5 py-4">
        {alerts.length ? (
          <div className="space-y-3 pr-1">
            {alerts.map((alert, index) => (
              <article
                key={alert.id}
                className="group relative overflow-hidden rounded-2xl border border-slate-200/90 bg-white p-4 transition hover:border-slate-300 hover:shadow-lg"
              >
                <div className={`absolute inset-y-0 left-0 w-1.5 bg-gradient-to-b ${riskGlow[alert.risk] || riskGlow.Low}`} />
                <div className="flex items-start justify-between gap-3 pl-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <div className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">
                        #{String(index + 1).padStart(2, "0")}
                      </div>
                      <div className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-500">
                        <RadioTower className="h-3.5 w-3.5" />
                        Live trigger
                      </div>
                    </div>
                    <p className="mt-3 text-sm font-semibold text-slate-950">{alert.zoneName}</p>
                    <p className="mt-1 text-sm leading-6 text-slate-600">{alert.message}</p>
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-slate-500">
                      <span className="inline-flex items-center gap-1.5">
                        <Clock3 className="h-3.5 w-3.5" />
                        {new Date(alert.createdAt).toLocaleString()}
                      </span>
                      <span className="inline-flex items-center gap-1.5">
                        <Sparkles className="h-3.5 w-3.5" />
                        Count: {alert.count}
                      </span>
                    </div>
                  </div>
                  <span className={`${riskClass(alert.risk)} rounded-full`}>
                    {alert.risk}
                  </span>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-6 text-sm text-slate-500">
            Alerts will appear here when any running zone crosses high-risk thresholds.
          </div>
        )}
      </div>
    </section>
  );
}
